import type { SiteContent } from "./types";

const now = new Date().toISOString();

export const defaultSiteContent: SiteContent = {
  version: 1,
  updatedAt: now,
  settings: {
    siteName: "Eshmart Agrox",
    tagline: "Nigerian Produce. Exported with Integrity.",
    title: "Eshmart Agrox | Premium Nigerian Produce Export",
    description:
      "Premium grade Okra and Ugu exported from Nigeria to European markets with quality and transparency.",
    logoUrl: "/hero.png",
    faviconUrl: "/favicon.ico",
    currency: "NGN",
    currencySymbol: "₦",
    contactEmail: "exports@eshmartagrox.com",
    contactPhone: "+234 800 000 0000",
    address: "Lagos, Nigeria",
    showSearch: true,
    showCart: true,
    showUser: true,
  },
  navigation: [
    { id: "nav-1", label: "Home", href: "/", order: 1, isVisible: true },
    { id: "nav-2", label: "Portfolio", href: "/portfolio", order: 2, isVisible: true },
    { id: "nav-3", label: "Book Online", href: "/book-online", order: 3, isVisible: true },
    { id: "nav-4", label: "Shop", href: "/shop", order: 4, isVisible: true },
    { id: "nav-5", label: "Blog", href: "/blog", order: 5, isVisible: true },
    {
      id: "nav-6",
      label: "Track My Order",
      href: "/track-my-order",
      order: 6,
      isVisible: true,
    },
  ],
  hero: {
    image: "/hero.png",
    headline: "Nigerian Produce. Exported with Integrity.",
    subheadline:
      "We bridge the gap between Nigeria's finest farms and European markets, delivering premium grade Okra and Ugu with an unwavering commitment to quality and transparency.",
    ctaLabel: "View Our Products",
    ctaHref: "/shop",
    slides: [
      {
        id: "slide-1",
        image: "/hero.png",
        headline: "Nigerian Produce. Exported with Integrity.",
        subheadline:
          "We bridge the gap between Nigeria's finest farms and European markets, delivering premium grade Okra and Ugu with an unwavering commitment to quality and transparency.",
        ctaLabel: "View Our Products",
        ctaHref: "/shop",
      },
    ],
  },
  homeFeatures: {
    sectionTitle: "Our Produce",
    sectionSubtitle:
      "Premium Nigerian harvests meticulously selected for international prestige and exceptional freshness.",
    cards: [
      {
        id: "card-1",
        number: "(01)",
        title: "Export Grade Okra",
        description:
          "Hand-picked for uniform size and vibrant color, ensuring the highest standards for European markets.",
        image: "/hero.png",
        ctaLabel: "Inquire Now",
        ctaHref: "/book-online",
      },
      {
        id: "card-2",
        number: "(02)",
        title: "Premium Ugu Leaves",
        description:
          "Nutrient-dense Nigerian fluted pumpkin leaves, preserved for maximum freshness during rapid transit.",
        image: "/hero.png",
        ctaLabel: "Inquire Now",
        ctaHref: "/book-online",
      },
      {
        id: "card-3",
        number: "(03)",
        title: "Seasonal Specialities",
        description:
          "Beyond our core exports, we curate a selection of seasonal Nigerian produce tailored for luxury grocery retailers and bulk wholesalers in Europe.",
        image: "",
        ctaLabel: "View Availability",
        ctaHref: "/shop",
      },
    ],
  },
  homeQuality: {
    sectionTitle: "Meticulous Cultivation and Export Grade Quality Systems",
    mainImage: "/hero.png",
    secondaryImage: "/hero.png",
    blocks: [
      {
        id: "qb-1",
        title: "Ethical Cultivation",
        description:
          "Our okra and ugu cultivation begins with non-GMO seeds and organic soil enrichment. We employ advanced irrigation and pest-management systems that prioritize environmental health while maximizing nutrient density for the European market.",
      },
      {
        id: "qb-2",
        title: "Rigorous Export Audit",
        description:
          "Each harvest undergoes a multi-stage audit: physical uniformity analysis, residue testing, and rapid cooling. Our quality compliance ensures every batch meets phytosanitary standards for international trade.",
      },
    ],
  },
  callToAction: {
    title: "Start Your Export Inquiry",
    description:
      "Ready to source premium Nigerian okra and ugu? Share your requirements with our export experts and receive a customized quote for your international trade needs.",
    contactImage: "/images/contact.png",
    secondaryTitle: "From soil to shelf",
    secondaryDescription:
      "End-to-end traceability from Nigerian farms to European distribution.",
  },
  footer: {
    copyright: "© 2026 Eshmart Agrox. All rights reserved.",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com" },
      { platform: "Instagram", url: "https://instagram.com" },
    ],
    columns: [
      {
        id: "fc-1",
        title: "Company",
        links: [
          { label: "About", href: "/" },
          { label: "Portfolio", href: "/portfolio" },
        ],
      },
      {
        id: "fc-2",
        title: "Shop",
        links: [
          { label: "All Products", href: "/shop" },
          { label: "Okra", href: "/shop" },
        ],
      },
      {
        id: "fc-3",
        title: "Support",
        links: [
          { label: "Book Online", href: "/book-online" },
          { label: "Track Order", href: "/track-my-order" },
        ],
      },
      {
        id: "fc-4",
        title: "Contact",
        links: [
          { label: "exports@eshmartagrox.com", href: "mailto:exports@eshmartagrox.com" },
        ],
      },
    ],
  },
  shop: {
    bannerImage: "https://images.unsplash.com/photo-1514996937319-344454492b37?w=1600&q=80",
    bannerTitle: "Our Shop",
    sortOptions: [
      "Sort by: Featured",
      "Price: Low to High",
      "Price: High to Low",
      "Name: A to Z",
    ],
    filters: {
      productTypes: ["Okra", "Packaging", "Ugu"],
      priceOptions: ["NGN 8", "NGN 35"],
      lengthOptions: ["100m", "200m"],
      quantityOptions: ["10 Pack", "10 Seedlings", "20 Seedlings", "25 Pack"],
      sizeOptions: ["Large", "Medium", "Small"],
      weightOptions: ["1 kg", "100g", "2 kg", "250g", "3 kg", "500g", "50g"],
      browseOptions: ["All Products", "Okra", "Ugu", "Packaging"],
    },
    products: [
      {
        id: "prod-1",
        name: "Bio-degradable Produce Bags",
        price: 10,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Pack",
        size: null,
        weight: null,
        image: "https://images.unsplash.com/photo-1580910051074-6c3e9e7fa4b1?w=800&q=80",
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: "prod-2",
        name: "Protective Produce Nets",
        price: 8,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "25 Pack",
        size: null,
        weight: null,
        image: "https://images.unsplash.com/photo-1520975918681-2b7d8b9f4b43?w=800&q=80",
        isPublished: true,
        sortOrder: 2,
      },
      {
        id: "prod-3",
        name: "Export Produce Box",
        price: 35,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Pack",
        size: null,
        weight: null,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        isPublished: true,
        sortOrder: 3,
      },
      {
        id: "prod-4",
        name: "Dried Ugu Flakes",
        price: 22,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: null,
        size: "Small",
        weight: "100g",
        image: "https://images.unsplash.com/photo-1604079621714-2f7a6c7d3fd8?w=800&q=80",
        isPublished: true,
        sortOrder: 4,
      },
      {
        id: "prod-5",
        name: "Ugu Seedlings",
        price: 18,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Seedlings",
        size: "Medium",
        weight: null,
        image: "https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=800&q=80",
        isPublished: true,
        sortOrder: 5,
      },
      {
        id: "prod-6",
        name: "Fresh Ugu Leaves",
        price: 12,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "20 Seedlings",
        size: "Large",
        weight: "250g",
        image: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80",
        isPublished: true,
        sortOrder: 6,
      },
      {
        id: "prod-7",
        name: "Fresh Okra",
        price: 8,
        category: "Okra",
        priceRange: "NGN 8-35",
        length: "100m",
        quantity: "10 Pack",
        size: "Medium",
        weight: "500g",
        image: "https://images.unsplash.com/photo-1542831371-d531d36971e6?w=800&q=80",
        isPublished: true,
        sortOrder: 7,
      },
      {
        id: "prod-8",
        name: "Premium Okra",
        price: 35,
        category: "Okra",
        priceRange: "NGN 8-35",
        length: "200m",
        quantity: "25 Pack",
        size: "Large",
        weight: "2 kg",
        image: "https://images.unsplash.com/photo-1506806732259-39c2d0268443?w=800&q=80",
        isPublished: true,
        sortOrder: 8,
      },
    ],
  },
  portfolio: {
    pageTitle: "Portfolio",
    pageSubtitle: "Our export success stories and partnerships.",
    items: [
      {
        id: "port-1",
        title: "European Retail Partnership",
        description: "Premium okra supply chain for major UK grocer.",
        image: "https://images.unsplash.com/photo-1508873699372-7ae7beff5cfd?w=800&q=80",
        sortOrder: 1,
        isPublished: true,
      },
      {
        id: "port-2",
        title: "Ugu Export Program",
        description: "Year-round ugu leaves to Netherlands distributors.",
        image: "https://images.unsplash.com/photo-1520303412467-5fc0c0b5d9f8?w=800&q=80",
        sortOrder: 2,
        isPublished: true,
      },
      {
        id: "port-3",
        title: "Packaging Innovation",
        description: "Biodegradable export packaging rollout.",
        image: "https://images.unsplash.com/photo-1506765515384-028b60a970df?w=800&q=80",
        sortOrder: 3,
        isPublished: true,
      },
      {
        id: "port-4",
        title: "Farm Direct Sourcing",
        description: "Ethical cultivation partnerships in Southwest Nigeria.",
        image: "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?w=800&q=80",
        sortOrder: 4,
        isPublished: true,
      },
      {
        id: "port-5",
        title: "Cold Chain Excellence",
        description: "Rapid cooling and transit quality systems.",
        image: "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?w=800&q=80",
        sortOrder: 5,
        isPublished: true,
      },
      {
        id: "port-6",
        title: "Seasonal Specialties",
        description: "Curated seasonal produce for luxury retailers.",
        image: "https://images.unsplash.com/photo-1520975918681-2b7d8b9f4b43?w=800&q=80",
        sortOrder: 6,
        isPublished: true,
      },
    ],
  },
  services: {
    pageTitle: "Our Services",
    pageSubtitle: "Book a consultation with our export specialists.",
    services: [
      {
        id: "svc-1",
        title: "Export Consultation",
        duration: "30 minutes",
        image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80",
        price: "₦25,000",
        description: "Discuss your import requirements and product availability.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: "svc-2",
        title: "Quality Audit Walkthrough",
        duration: "45 minutes",
        image: "https://images.unsplash.com/photo-1531497865142-3d33f1d7b1b1?w=800&q=80",
        price: "₦40,000",
        description: "Review our cultivation and export compliance processes.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 2,
      },
      {
        id: "svc-3",
        title: "Custom Sourcing Plan",
        duration: "60 minutes",
        image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
        price: "₦55,000",
        description: "Tailored produce sourcing for your market.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 3,
      },
    ],
  },
  blog: {
    pageTitle: "Blog",
    pageSubtitle: "News and insights from Eshmart Agrox.",
    posts: [
      {
        id: "post-1",
        title: "Exporting Nigerian Okra to Europe",
        slug: "exporting-nigerian-okra",
        excerpt: "What European buyers look for in premium okra.",
        content:
          "European markets demand uniform size, vibrant color, and strict phytosanitary compliance...",
        coverImage: "/hero.png",
        author: "Eshmart Team",
        publishedAt: now,
        isPublished: true,
        tags: ["okra", "export"],
      },
    ],
  },
  trackOrder: {
    pageTitle: "Track My Order",
    pageDescription: "Enter your order number to check shipment status.",
    orders: [
      {
        id: "ord-1",
        orderNumber: "EA-2026-001",
        customerName: "Sample Customer",
        customerEmail: "customer@example.com",
        status: "processing",
        items: [{ productName: "Fresh Okra", quantity: 2, price: 8 }],
        total: 16,
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
};
